# File: configs/experiment_config.yaml

# -- Data Paths --
data_source_arena: "lmsys/chatbot_arena_conversations"
data_source_hh: "Anthropic/hh-rlhf"
cache_dir: "cache/"
results_dir: "results/"

# -- Model Architecture --
embedding_dim: 384
num_experts_K: 2
low_rank_r: 16
prompt_encoder_model: "sentence-transformers/all-MiniLM-L6-v2"

# -- Global Pre-training Hyperparameters --
global_learning_rate: 0.001
global_weight_decay: 0.0001
global_batch_size: 512
global_epochs: 3

# -- Per-User Personalization Hyperparameters --
user_learning_rate: 0.05
user_l2_regularization: 0.001

# -- Experiment Settings --
min_votes_per_user: 50
random_seed: 42